version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mydatabase
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: WS-AI-VS
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  app:
    image: whisper_subtitle
    container_name: myapp
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: WS-AI-VS
    ports:
      - "4000:8000"
    depends_on:
      - db
